version: "3.3"
services:
  pgadmin:
    ports:
      - "5050:5050"

  backend:
    volumes:
      - ./app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    networks:
      - backend
    build:
      context: .
      dockerfile: backend.dockerfile
      args:
        INSTALL_DEV: ${INSTALL_DEV-true}
