version: "3.3"
services:
  pgadmin:
    ports:
      - "5050:5050"

  queue:
    ports:
      - "5672:5672"

  backend:
    volumes:
      - ./app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    networks:
      - backend
    build:
      context: .
      dockerfile: backend.dockerfile
    command: bash -c "python app/initial_data.py && uvicorn --reload --host 0.0.0.0 app.main:app"

  celeryworker:
    volumes:
      - ./app:/app
    command: bash -c "celery worker -A app.tasks.batch_upload -l info -Q batch-upload -c 1"
