version: "3.3"
services:
  pgadmin:
    ports:
      - "5050:5050"

  backend:
    volumes:
      - ./app:/app
    environment:
      - SERVER_HOST=http://${DOMAIN?Variable not set}
    networks:
      - backend
    build:
      context: .
      dockerfile: backend.dockerfile

  celeryworker:
    volumes:
      - ./app:/app
    command: bash -c "celery worker -A app.tasks.batch_upload -l info -Q batch-upload -c 1"
